### ISSUE TITLE
No pdf for feature associations when only 1 species is significant

### ISSUE THREAD

**Issue by apalleja** [zellerlab/siamcat#1]
Hi SIAMCAT developers,

I like very much your package! However when I run:
plot.title=paste0("assoc_", analysis, ".pdf")
check.associations(
    siamcat,
    sort.by = 'fc',
    fn.plot = plot.title,
    alpha = 0.1,
    mult.corr = "fdr",
    detect.lim = 10 ^ -6,
    max.show = 50,
    plot.type = "quantile.box",
    panels = c("fc", "prevalence", "auroc"),
    verbose = 2
)

I get this error and don't get any pdf for the significant species. It does not happen if I set the alpha much higher because then I have 3 species significant.

+ starting check.associations
+ starting analyse.binary.marker
+++ calculating effect size for each feature.
  |=======================================================================================================================================| 100%+++ found 1 significant associations at a significance level < 0.1
+ finished analyse.binary.marker in 0.356 s
Error: Argument 'x' is of class 'numeric', but should be a matrix. The use of a 'numeric' is not supported, the correctness of the result is not guaranteed. Please update your code accordingly.
In addition: Warning message:
In analyse.binary.marker(feat = feat, label = label, detect.lim = detect.lim,  :
  Less than 5 associations found. Consider changing your alpha
            value

Please let me know if there is a quick fix for this ;P

Albert

**Comment by jakob-wirbel** [comment]
Hello Albert,

the quickest fix would be to up your alpha a bit, because it seems that there are fewer than 5  significant associations at your chosen alpha level. You could try 
`alpha=0.2` 
in your function call (or any higher alpha) and check the results.

But indeed, there seems to be a bug which we will try to fix soon :-)

Cheers,
Jakob

**Comment by jakob-wirbel** [comment]
The association plot should work already when you chose as `plot.type` one of these two:
- `box`
- `bean`

The quantile plots should be fixed with [this commit](https://github.com/zellerlab/siamcat/commit/418e3d0c2f2c0588d668ebeb2d8197ca5c7fa50e) now, i hope 😄
