### ISSUE TITLE
check.confounders leaves empty object during tutorial

### ISSUE THREAD

**Issue by drelo** [zellerlab/siamcat#31]
Dear all, 

I just installed the software and I am following this[ tutorial ](https://bioconductor.org/packages/release/bioc/vignettes/SIAMCAT/inst/doc/SIAMCAT_vignette.html) 

Everything seems fine until this step
`sc.obj <- check.confounders(sc.obj,  fn.plot = 'confounder_plots.pdf',  meta.in = NULL,  feature.type = 'filtered' )` 

If I skip this step above I can proceed to the following step normalizing the data
`sc.obj <- normalize.features(sc.obj, norm.method = "log.unit", norm.param = list( log.n0 = 1e-06, n.p = 2, norm.margin = 1))`.

But if I execute it I get the plot which looks slightly different than the vignette -but maybe that's not relevant- printing this info

```
++ metadata variables:
	AJCC_stage & Group
++ are nested inside the label and have been removed from this analysis
Finished checking metadata for confounders, results plotted to: confounder_plots.pdf
```
but the object sc.obj appears as NULL

This is the sc.obj just before that, just  'filter'

```
siamcat-class object
label()                Label object:         88 CTR and 53 CRC samples
filt_feat()            Filtered features:    300 features after abundance filtering

contains phyloseq-class experiment-level object @phyloseq:
phyloseq@otu_table()   OTU Table:            [ 1754 taxa and 141 samples ]
phyloseq@sam_data()    Sample Data:          [ 141 samples by 6 sample variables ]
```
I can provide more details if needed. Using the devtools version of siamcat (SIAMCAT_1.13.4)

This issue is not crucial at the moment for me but I thought a heads up would be useful.
Thanks for your help.

**Comment by jakob-wirbel** [comment]
Hi @drelo,
thank you for pointing this out! This is an error in the main vignette since the `check.confounder` function does not return anything. Instead, it only produces the plot visualizing the confounder checks. This is the reason why `sc.obj` is `NULL` after you execute this part of the vignette. 
Thanks for spotting the error and opening the issue! I am working on a new version anyway and will fix it in the new vignette soon
Cheers,
Jakob

**Comment by drelo** [comment]
Thanks for the clarification!
