### ISSUE TITLE
How top do you pick 20 features in association.plot() function?

### ISSUE THREAD

**Issue by fernando-aq** [zellerlab/siamcat#41]
Hi, I am wondering how the top N features are selected in your association.plot(max.show = N) function?

Is it based on absolute fold change? or any other parameters?

**Comment by jakob-wirbel** [comment]
Hi @fernando-aq 
It depends on how you sort the table. By default, the features will be sorted by generalized fold change, so the N features with the largest absolute fold change will be chosen (if you have more than `max.show` significant features). 
You can also just extract the association results using 
```associations(sc.obj)```
and then investigate the whole table with other R functions that you like 
Cheers,
Jakob
