### ISSUE TITLE
How do you determine which features are the top one?

### ISSUE THREAD

**Issue by fernando-aq** [zellerlab/siamcat#43]
Hi, I want to manually plot the result from your association.plot() function using GGPLOT2.

I managed to extract the data from the siamcat object, but confused about which feature represents the top 20 of the test. 
Is it sorted based on the highest absolute fold change? or the p adj value? or taking into account both? 

Say I ran the code below code:
association.plot(siamcat_object, sort.by = 'fc', fn.plot = NULL,  max.show = 20, panels = c('fc', 'auroc'))

When I sort the data obtained by extracting from the siamcat object, the result did not give the same order as what is plotted using the function association.plot()

**Comment by fernando-aq** [comment]
Hello there?

**Comment by jakob-wirbel** [comment]
which order did you get when you sort it outside of SIAMCAT?
Usually the top 20 features are taken based on the p-value, and then sorted by fold change

**Comment by fernando-aq** [comment]
I ordered the features with padj value below the 0.05 or 0.01 depending on the association.test function.
