### ISSUE TITLE
integrate biomass into siamcat

### ISSUE THREAD

**Issue by tapj** [zellerlab/siamcat#46]
Hi,

I have biomass data (or total cell count per sample), How can I train a model integrating this biomass parameter.

I do not want biomass as confounding factor but as feature predictor.

++
Ju.

**Comment by jakob-wirbel** [comment]
Hi @tapj 
Hope all is well with you! :)

This should not be a big problem. If you have the biomass parameter in your metadata, you can use the 
`add.meta.pred` function to add it as an additional predictor to the dataframe of bacterial abundances. It will be standardized by default, but you can turn this off, I think. So the best would be to add it to the feature data after the data normalization step and then train the model. If it is important for the prediction of the outcome, it will be selected by the Lasso or the Random Forest classifier.

Let me know if this works!

**Comment by tapj** [comment]
Thank you Jakob for your fast reply, I haven't noticed this function in siamcat.
