### ISSUE TITLE
Incorrect LOOCV split via create.data.split

### ISSUE THREAD

**Issue by akg2685** [zellerlab/siamcat#6]
The documentation suggests that it may be possible to perform leave one out cross validation (LOOCV) with create.data.split by setting num.folds equal to n, where n is the total number of samples.  While the verbose output of the function claims that this is what is happening, the function actually creates n-1 folds and always puts two samples in the first test fold.

Additionally (though I'm not sure how related it is), the siamcat object produced by attempting LOOCV with num.folds = n in create.data.split fails in make.predictions with the following error message:

Error in make.predictions(siamcat) : 
  nrow(data) == length(test.label) is not TRUE

These issues are reproducible using the data and procedure from the SIAMCAT basic vignette.

**Comment by jakob-wirbel** [comment]
Thanks for catching this!
I'm at a conference at the moment, but i will check why this is happening once i'm back
